version: '3'

services:
  postgres:
    container_name: user_postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: microserviceUser
      POSTGRES_USER: user_postgres_user
      POSTGRES_PASSWORD: 63&:c4Acl3}^
    ports:
      - 5432:5432

  web:
    container_name: apiUser
    build: .
    command: bash -c "python manage.py migrate && echo \"from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('admin', 'admin@unipam.edu.br', '${PASS_ADMIN}')\" | python manage.py shell && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: always
    
